Exam/FinalExam/FinalExam/Models/Runner.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FinalExam.Models
{
    public class Runner
    {
        public int RunnerId { get; set; }
        [Required]
        [StringLength(100)]
        public string FirstName { get; set; }
        [Required]
        [StringLength(100)]
        public string LastName { get; set; }
        [Required]
        public DateTime BirthDate { get; set; }
        [Required]
        public Gender Gender { get; set; }
        [Required]
        [StringLength(100)]
        public string Email { get; set; }
        [Required]
        public string Telephone { get; set; }
        [Required]
        [StringLength(255)]
        public string City { get; set; }
        [Required]
        [StringLength(255)]
        public string Address { get; set; }
        public string PostalCode { get; set; }
        [Required]
        public int CountryId { get; set; }
        [Required]
        public DateTime RegistrationDate { get; set; }
        [Required]
        public string ContactPersonName { get; set; }
        [Required]
        public string ContactPersonTelephone { get; set; }
        public int EventId { get; set; }
        public Event Event { get; set; }
        public Country Country { get; set; }
    }
}

Exam/FinalExam/FinalExam/Controllers/RunnersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FinalExam.Models;
using PagedList;

namespace FinalExam.Controllers
{
    public class RunnersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Runners
        public ActionResult Index(string sortDir, string currentFilter, string searchString, int? page, string sortOrder = "")
        {
            if (searchString != null)
                page = 1;
            else
                searchString = currentFilter;

            ViewBag.CurrentFilter = searchString;
            ViewBag.sortOrder = sortOrder;
            ViewBag.sortDir = sortDir;

            var query = from r in db.Runners.Include(r => r.Event).AsQueryable()
                        select new RunnerViewModelForList()
                        {
                            RunnerId = r.RunnerId,
                            Name = r.FirstName + " " + r.LastName,
                            Email = r.Email,
                            Gender = r.Gender.ToString(),
                            Telephone = r.Telephone,
                            EventName = r.Event.Name,
                            EventStatus = r.Event.IsClosed ? "Closed" : "Open"
                        };
            if (!string.IsNullOrEmpty(searchString))
                query = query.Where(s => s.Name.Contains(searchString));
            switch (sortOrder.ToLower())
            {
                case "name":
                    if (sortDir.ToLower() == "desc")
                        query = query.OrderByDescending(p => p.Name);
                    else
                        query = query.OrderBy(p => p.Name);
                    break;
                case "gender":
                    if (sortDir.ToLower() == "desc")
                        query = query.OrderByDescending(p => p.Gender);
                    else
                        query = query.OrderBy(p => p.Gender);
                    break;
                case "email":
                    if (sortDir.ToLower() == "desc")
                        query = query.OrderByDescending(p => p.Email);
                    else
                        query = query.OrderBy(p => p.Email);
                    break;
                case "telephone":
                    if (sortDir.ToLower() == "desc")
                        query = query.OrderByDescending(p => p.Telephone);
                    else
                        query = query.OrderBy(p => p.Telephone);
                    break;
                case "eventname":
                    if (sortDir.ToLower() == "desc")
                        query = query.OrderByDescending(p => p.EventName);
                    else
                        query = query.OrderBy(p => p.EventName);
                    break;
                case "eventstatus":
                    if (sortDir.ToLower() == "desc")
                        query = query.OrderByDescending(p => p.EventStatus);
                    else
                        query = query.OrderBy(p => p.EventStatus);
                    break;
                default:
                    query = query.OrderBy(p => p.Name);
                    break;
            }

            int pageSize = 2;
            int pageNumber = (page ?? 1);
            var data = query.ToPagedList(pageNumber, pageSize);
            if (Request.IsAjaxRequest())
                return PartialView("_RunnersList", data);
            else
                return View(data);
        }

        // GET: Runners/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Runner runner = db.Runners.Find(id);
            if (runner == null)
            {
                return HttpNotFound();
            }
            return View(runner);
        }

        // GET: Runners/Create
        public ActionResult Create()
        {
            ViewBag.CountryId = new SelectList(db.Countries, "Id", "Name");
            ViewBag.EventId = new SelectList(db.Events, "Id", "Name");
            return View();
        }

        // POST: Runners/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RunnerViewModelEdit runnerVM)
        {
            if (ModelState.IsValid)
            {
                Runner runner = new Runner()
                {
                    FirstName = runnerVM.FirstName,
                    LastName = runnerVM.LastName,
                    Email = runnerVM.Email,
                    Gender = runnerVM.Gender,
                    BirthDate = runnerVM.BirthDate,
                    Address = runnerVM.Address,
                    CountryId = runnerVM.CountryId,
                    EventId = runnerVM.EventId,
                    Telephone = runnerVM.Telephone,
                    City = runnerVM.City,
                    PostalCode = runnerVM.PostalCode,
                    RegistrationDate = DateTime.Now,
                    ContactPersonName = runnerVM.ContactPersonName,
                    ContactPersonTelephone = runnerVM.ContactPersonTelephone
                };

                if (!IsEventClosed(runnerVM.EventId))
                {
                    db.Runners.Add(runner);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                    ModelState.AddModelError("EventId", "The selected event is closed.");
            }
            ViewBag.CountryId = new SelectList(db.Countries, "Id", "Name", runnerVM.CountryId);
            ViewBag.EventId = new SelectList(db.Events, "Id", "Name", runnerVM.EventId);
            return View(runnerVM);
        }
        private bool IsEventClosed(int eventId)
        {
            Event @event = db.Events.Where(e => e.Id == eventId).FirstOrDefault();
            if (@event != null && @event.IsClosed)
                return true;
            return false;
        }

        private RunnerViewModelEdit GetRunnerViewModel(Runner runner)
        {
            RunnerViewModelEdit runnerVM = new RunnerViewModelEdit()
            {
                Id = runner.RunnerId,
                FirstName = runner.FirstName,
                LastName = runner.LastName,
                Email = runner.Email,
                Gender = runner.Gender,
                BirthDate = runner.BirthDate,
                Address = runner.Address,
                CountryId = runner.CountryId,
                EventId = runner.EventId,
                Telephone = runner.Telephone,
                City = runner.City,
                PostalCode = runner.PostalCode,
                RegistrationDate = DateTime.Now,
                ContactPersonName = runner.ContactPersonName,
                ContactPersonTelephone = runner.ContactPersonTelephone
            };
            return runnerVM;
        }
        // GET: Runners/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Runner runner = db.Runners.Find(id);
            if (runner == null)
            {
                return HttpNotFound();
            }
            var runnerVM = GetRunnerViewModel(runner);

            ViewBag.CountryId = new SelectList(db.Countries, "Id", "Name", runnerVM.CountryId);
            ViewBag.EventId = new SelectList(db.Events, "Id", "Name", runnerVM.EventId);
            return View(runnerVM);
        }

        // POST: Runners/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RunnerViewModelEdit runnerVM)
        {
            if (ModelState.IsValid)
            {
                Runner runner = db.Runners.Find(runnerVM.Id);
                runner.FirstName = runnerVM.FirstName;
                runner.LastName = runnerVM.LastName;
                runner.Email = runnerVM.Email;
                runner.Gender = runnerVM.Gender;
                runner.BirthDate = runnerVM.BirthDate;
                runner.Address = runnerVM.Address;
                runner.CountryId = runnerVM.CountryId;
                runner.EventId = runnerVM.EventId;
                runner.Telephone = runnerVM.Telephone;
                runner.City = runnerVM.City;
                runner.PostalCode = runnerVM.PostalCode;
                runner.ContactPersonName = runnerVM.ContactPersonName;
                runner.ContactPersonTelephone = runnerVM.ContactPersonTelephone;

                if (!IsEventClosed(runnerVM.EventId))
                {
                    db.Entry(runner).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                    ModelState.AddModelError("EventId", "The selected event is closed.");
            }
            ViewBag.CountryId = new SelectList(db.Countries, "Id", "Name", runnerVM.CountryId);
            ViewBag.EventId = new SelectList(db.Events, "Id", "Name", runnerVM.EventId);
            return View(runnerVM);
        }

        // GET: Runners/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Runner runner = db.Runners.Find(id);

Exam/FinalExam/FinalExam/Views/Runners/Create.cshtml
@model FinalExam.Models.RunnerViewModelEdit

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Runner</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Gender, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telephone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telephone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telephone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CountryId, "CountryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CountryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CountryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactPersonName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactPersonName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactPersonName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactPersonTelephone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactPersonTelephone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactPersonTelephone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventId, "EventId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EventId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EventId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Exam/FinalExam/FinalExam/Views/Runners/Delete.cshtml
@model FinalExam.Models.Runner

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Runner</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Country.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Event.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Event.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telephone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostalCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegistrationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistrationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactPersonName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactPersonName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactPersonTelephone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactPersonTelephone)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Exam/FinalExam/FinalExam/Views/Runners/Details.cshtml
@model FinalExam.Models.Runner

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Runner</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Country.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Event.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Event.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telephone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostalCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegistrationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistrationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactPersonName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactPersonName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactPersonTelephone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactPersonTelephone)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.RunnerId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Exam/FinalExam/FinalExam/Views/Runners/Edit.cshtml
@model FinalExam.Models.RunnerViewModelEdit

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Runner</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Gender, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telephone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telephone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telephone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CountryId, "CountryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CountryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CountryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactPersonName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactPersonName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactPersonName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactPersonTelephone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactPersonTelephone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactPersonTelephone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventId, "EventId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EventId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EventId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Exam/FinalExam/FinalExam/Views/Runners/Index.cshtml
@using PagedList
@model IPagedList<FinalExam.Models.RunnerViewModelForList>
<h2>Runners</h2>
<p>@Html.ActionLink("Create New", "Create")</p>
<div class="row">
    <div class="col-md-3">
        @using (Ajax.BeginForm("Index", "Runners", new AjaxOptions() { HttpMethod = "GET", InsertionMode = InsertionMode.Replace, UpdateTargetId = "grid" }))
        {
            <div class="input-group addon">
                <input class="form-control" placeholder="Name" name="searchString" type="text" value="@ViewBag.CurrentFilter" />
                <div class="input-group-btn">
                    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                </div>
            </div>
        }
    </div>
</div>
<div id="grid">@Html.Partial("_RunnersList", Model)</div>
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery.signalR-2.1.2.min.js"></script>
    <script src="/signalr/hubs"></script>
    <script>
    $(document).ready(function () {
        var myHub = $.connection.myHub;
        myHub.client.updateClient = function () {
            $.ajax({
                cache: false,
                type: "GET",
                url: '/Runners',
                success: function (data) {
                    $('#grid').html(data);
                }
            });
        };
        $.connection.hub.start().done(function () { });
    });
    </script>
}